basePath: /
definitions:
  beef.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  beef.GetSummaryResponse:
    properties:
      beef:
        additionalProperties:
          type: integer
        type: object
    type: object
info:
  contact: {}
  description: This is the API for the Pie Fire Dire application.
  title: Pie Fire Dire
  version: "1.0"
paths:
  /api/{version}/beef:
    get:
      parameters:
      - description: App Version
        enum:
        - v1
        in: path
        name: version
        required: true
        type: string
      produces:
      - application/json
      responses:
        "501":
          description: Not Implemented
          schema:
            $ref: '#/definitions/beef.ErrorResponse'
      summary: Get beef details
      tags:
      - Beef
  /api/{version}/beef/summary:
    get:
      parameters:
      - description: App Version
        enum:
        - v1
        in: path
        name: version
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/beef.GetSummaryResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/beef.ErrorResponse'
      summary: Get beef summary
      tags:
      - Beef
swagger: "2.0"
